Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -84,7 +84,7 @@ jobs:
       # step 4: Initialize EB CLI with debug output
       - name: Initialize EB CLI
         run: |
-          eb init my-app --platform java --region us-west-2 --debug || { echo "EB list failed" ; exit 1; }
+          eb init my-app --platform java --region us-west-2 --debug || { echo "EB init failed" ; exit 1; }
 
       # Step 5: List Elastic BeanStalk environments to confirm existence
       - name: List EB environments
@@ -101,4 +101,4 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: 'us-west-2'
         run: |
-          eb deploy --debug || { echo "EB deploy failed"; exit 1; }
+          eb deploy my-environment --debug || { echo "EB deploy failed"; exit 1; }
