Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -81,24 +81,37 @@ jobs:
           pip install --upgrade awsebcli
           eb --version
 
-      # step 4: Initialize EB CLI with debug output
+      # Step 4: Configure AWS CLI with Credentials
+      - name: Configure AWS CLI
+        run: |
+          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws configure set region us-west-2
+        
+      # step 5: Initialize EB CLI with debug output
       - name: Initialize EB CLI
         run: |
           eb init my-app --platform java --region us-west-2 --debug || { echo "EB init failed" ; exit 1; }
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: 'us-west-2'
 
-      # Step 5: List Elastic BeanStalk environments to confirm existence
+      # Step 6: List Elastic BeanStalk environments 
       - name: List EB environments
-        run: eb list --region usd-west-2 --debug || { echo "EB list failed" ; exit 1; }
+        run: |
+          eb list --region us-west-2 --debug || { echo "EB list failed" ; exit 1; }
 
-      # Step 6: Verify WAR file exists
+      # Step 7: Verify WAR file exists
       - name: Verify WAR files exists
-        run: ls -la ./App/target/*.war || echo " No WAR file found"
+        run: |
+          ls -la ./App/target/*.war || echo " No WAR file found"
 
-      # Step 7: Deploy to AWS Elastic Beanstalk
+      # Step 8: Deploy to AWS Elastic Beanstalk
       - name: Deploy to AWS Elastic Beanstalk
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: 'us-west-2'
         run: |
-          eb deploy my-environment --debug || { echo "EB deploy failed"; exit 1; }
+          eb deploy --debug || { echo "EB deploy failed"; exit 1; }
