Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -92,23 +92,26 @@ jobs:
           aws configure set region us-west-2
           aws sts get-caller-identity
 
-      #5 Step 5: Check target directory for WAR file 
+      #5 Step 5: Check the target directory for the WAR file 
       - name: Check target directory for WAR file 
         run: |
           echo "Checking for WAR file"
           ls -la ./target || { echo "Target directory not found or empty"; exit 1 }
           ls -la ./target/*.war || ( echo "WAR file not found"; exit 1; }
-        
-      # step 6: Initialize EB CLI with debug output
-      - name: Initialize EB CLI
-        run: |
-          eb init my-app --platform java --region us-west-2 --debug || { echo "EB init failed" ; exit 1; }
-      # Step 7: List Elastic BeanStalk environments 
-      - name: List EB environments
-        run: |
-          eb list --region us-west-2 --debug || { echo "EB list failed" ; exit 1; }
 
-      # Step 8: Deploy to AWS Elastic Beanstalk
+      # Step 6: Initializing EB CLI and verifying application and environment
+      - name: Initialize Elastic Beanstalk CLI
+        run: |
+          echo "Initializing EB CLI for application and environment"
+          eb init -p java my-app --region us-west-2 --debug || { echo "EB init failed"; exit 1; }
+
+      - name: Check EB Environments
+        run: |
+          echo "Listing EB environments to verify existence"
+          eb list --region us-west-2 --debug || { echo "EB list failed"; exit 1; }
+
+      # step 7: Deploy to AWS Elastic Beanstalk
       - name: Deploy to AWS Elastic Beanstalk
         run: |
+          echo "Attempting to deploy application"
           eb deploy --debug || { echo "EB deploy failed"; exit 1; }
